name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'ui'
            split_repository: 'monorepo-ui'

    steps:
      -   uses: actions/checkout@v3

      # no tag
      -
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
#          repository_organization: 'wambugudavis'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
#          repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "wambugudavis"
          user_email: "davvey27@gmail.com"
